### ISSUE TITLE
Use `!default` variables in components to allow easier overrides

### ISSUE THREAD

**Issue by RossMcMillan92** [alphagov/govuk-frontend#1159]
Hey,

I'm working on a project where we need to override some colours in the govuk components.

Button for example: https://github.com/alphagov/govuk-frontend/blob/master/src/components/button/_button.scss

```scss
// _button.scss
$govuk-button-colour: #00823b;
$govuk-button-hover-colour: darken($govuk-button-colour, 5%);
$govuk-button-shadow-colour: darken($govuk-button-colour, 15%);
$govuk-button-text-colour: govuk-colour("white");
```

Since these variables don't have the default flag, to override the button colours we need to do:

```scss
@import 'govuk-frontend/components/button/button';

.govuk-button {
  background-color: $custom-color;
  box-shadow: 0 $button-shadow-size 0 $custom-shadow-color;
  // etc...
}
```

This is prone to human-error as we need to copy all class names and specific rules. Ideally, with default flags, we'd be able to do the following which is much safer:

```scss
$govuk-button-colour: $custom-color;
$govuk-button-hover-colour: $custom-color;
$govuk-button-shadow-colour: $custom-color;
$govuk-button-text-colour: $custom-color;

@import 'govuk-frontend/components/button/button';
```

I see default flags are set up for the global variables under `/settings`, but is there a reason they're not set up for component variables? If not, I'd be more than happy to submit a PR to change this.

Thanks!
