### ISSUE TITLE
Excess margin on checkboxes and radios where last item is conditionally revealed

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1260]
On the checkboxes and radios there's a rule removing the `margin-bottom` from the last item - I assume because it's already got margin coming from the `govuk-form-group`.

![Screenshot 2019-03-28 at 15 22 29](https://user-images.githubusercontent.com/2204224/55169826-5c19f180-516d-11e9-80db-cfd48f3bee78.png)

However, if the last radio or checkbox has a conditionally revealed item, this margin _isn't_ removed - I assume because whist it's visually the last item, there's actually another item in the dom after it.

![Screenshot 2019-03-28 at 15 22 42](https://user-images.githubusercontent.com/2204224/55169892-7d7add80-516d-11e9-8a0f-14bb7d6210dd.png)

**Comment by nickcolley** [comment]
I think this could be solved in two ways:

1. Adding a class applied when iterating over items in the template
2. Using a selector that relies on the ordering of items and conditional reveals, since there is no previous sibling selector in CSS.

```css
.govuk-checkboxes__item:nth-last-of-type(2):not(:last-of-type) {
    margin-bottom: 0;
}
```
```css
.govuk-radios__item:nth-last-of-type(2):not(:last-of-type) {
    margin-bottom: 0;
}
```
