### ISSUE TITLE
Indeterminate checkboxes aren't reflected visually

### ISSUE THREAD

**Issue by adamsilver** [alphagov/govuk-frontend#1453]
There's a rare-ish state on checkboxes known as indeterminate.

As the GOV.UK checkboxes are custom when this state is true, the state is not reflected visually.

![image](https://user-images.githubusercontent.com/37163/59448029-3f03cf00-8dfc-11e9-9204-c18771fb7eae.png)

I've only seen this in use for (de)select all checkboxes used as a makeshift button to select all items, usually in a table. That's what we, at MOJ, are using it for.

Further reading:
https://css-tricks.com/indeterminate-checkboxes/

**Comment by nickcolley** [comment]
Heya Adam,

I prototyped this in the backlog thread here: https://github.com/alphagov/govuk-design-system-backlog/issues/37#issuecomment-429372272

The code looks like:

```css
.govuk-checkboxes__input:indeterminate + .govuk-checkboxes__label::after {
  transform: rotate(0);
  border: none;
  top: 0;
  bottom: 0;
  margin: auto;
  height: 6px;
  width: 22px;
  background: currentColor;
  opacity: 1;
}
```

Note, you'd want to make sure small checkboxes work too.
