### ISSUE TITLE
Skip link component loses underline when global styles are enabled

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#1641]
When the `$govuk-global-styles: true;` option is enabled, the [skip link component](https://design-system.service.gov.uk/components/skip-link/) does not have an underline.

This can be seen if you download the GOV.UK Prototype Kit, which has the option enabled by default.

The lack of underline is because the link acquires the default focus style of being black-on-yellow with a black bottom-border:

```css
.govuk-link:focus, a:focus {
  outline: 3px solid transparent;
  color: #0b0c0c;
  background-color: #ffdd00;
  box-shadow: 0 -2px #ffdd00, 0 4px #0b0c0c;
  text-decoration: none;
}
```
