### ISSUE TITLE
Media query with $until fails

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1674]
I think I have a bug with the media queries.

The following will not work:
<img width="616" alt="Screenshot 2019-12-06 at 10 24 36" src="https://user-images.githubusercontent.com/2204224/70322786-eea58100-1822-11ea-87f8-fda4565e36eb.png">

If I change to `$from: tablet` it's fine. Weirdly it doesn't cause a compiler issue -but the css doesn't seem to be output.

When trying with extend I get an error with the extend - but I think it's related to this mixin.

**Comment by nickcolley** [comment]
Hey @edwardhorsford,

I've tried to reproduce your issue here:

https://govuk-frontend-issue-1674.glitch.me

```scss
html::before {
  position: absolute;
  background: white;
  padding: 5px;
  font-family: sans-serif;
  @extend %until-mobile-only;
  @extend %mobile-only;
}

%until-mobile-only {
  @include govuk-media-query($until: mobile) {
    content: 'govuk-media-query($until: mobile)';
  }
}

%mobile-only {
  @include govuk-media-query(mobile) {
    content: 'govuk-media-query(mobile)';
  }
}
```

And it seems to output as expected, could you provide some steps to reproduce the issue you're running into please?
