### ISSUE TITLE
Should the `iff` function be public or namespaced?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1735]
Something I noticed when doing the work to show the sass docs is that the `iff` function is the odd one out. It is public but does not have `govuk-` namespace.
Proposals
1. make it private by changing it's name to `_iff` and updating sass docs
2. make it consistent by changing it's name to `govuk-iff`

My preference would be to make it private since it's not a GOV.UK Frontend specific thing and is really an internal function.

- [Source code](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/tools/_iff.scss#L13-L15)

**Comment by 36degrees** [comment]
We could also consider removing if and just using Sass' built-in `if` function – I don't think it'd make sense to rename it to `govuk-iff` as we lose all the benefits of conciseness over `if`.

Have we seen any evidence of this causing issues for users?

**Comment by nickcolley** [comment]
> Have we seen any evidence of this causing issues for users?

No evidence other than when generating the Sass docs it creates an inconsistency and we'd then be promoting something that feels like we made a mistake on.

I also think there's likely not much use of this function yet so would prefer sort it out before having it document, or as my preference would be to make it private.

We could make it private without changing the name of course.

**Comment by 36degrees** [comment]
For context, this was added as 'syntactic sugar' for situations like this:

```scss
@mixin govuk-typography-weight-regular($important: false) {
  font-weight: $govuk-font-weight-regular iff($important, !important);
}
```

Sass' default `if` function always requires you to pass an `else` clause:

```scss
.foo {
  font-weight: $govuk-font-weight-regular if($important, !important, ""); 
}
```
