### ISSUE TITLE
Best practice overriding variables in components

### ISSUE THREAD

**Issue by apricot13** [alphagov/govuk-frontend#1938]
I'm having an issue working out the best way to override certain variables in components.

Here is my scss simplified:

_application.scss_
```scss
$govuk-footer-text: $nevada;

@import "~govuk-frontend/govuk/all";
```

the imported code relevant to my import is
```scss
@include govuk-exports("govuk/component/footer") {
  $govuk-footer-text: $govuk-text-colour;
}
```

If I change the component code to this it will work
```scss
@include govuk-exports("govuk/component/footer") {
  $govuk-footer-text: $govuk-text-colour !default;
}
```

My question is what is best practice here? are there only certain variables I should overwrite?
