### ISSUE TITLE
Invalid examples in new fixtures files

### ISSUE THREAD

**Issue by andymantell** [alphagov/govuk-frontend#1962]
I am currently going through implementing the new fixtures released as part of 3.9.0 and have encountered an issue with some of the new hidden examples. Take the following from date input:

```
- name: with values
  hidden: true
  data:
    items:
      -
        id: day
      -
        id: month
      -
        id: year
        value: 2018
```

This example is missing `name` and `label` keys from each item which are marked as `required: true` in the specification of the component. This is just one instance of this kind of issue, I have encountered several others (_Happy to compile a list of all the issues once we've bottomed out the discussion..._)

I _think_ I would expect all the examples in these files to be valid relative to the specification. It's causing me a slight issue in govuk-react-jsx whereby my components do not expect these values to be un-set. I had started to embark on making the components more resilient, but thought I would open this ticket before I go too far. I could make my components handle these invalid examples by guarding against these kinds of things, but is that the _right_ thing to do? If people were omitting these attributes whilst _actually_ using my library in the wild, it would be outputting incorrect markup - I actually want my library to throw errors when people do this, not silently swallow them.

Which leads me to think I don't want to guard against this, and that the base examples _should_ be valid relative to the spec.

What do you think? Perhaps the build tool could even be validating examples against the spec to ensure these don't get through.

**Comment by andymantell** [comment]
Incidentally, `label` shouldn't actually be marked as required for date input items. If you omit `label` then `name` gets used instead.

**Comment by andymantell** [comment]
I retract the statement that there are other examples - this is the only one I've found so far (I was wrong about the others).

So I think it still stands that this date example is needs name attributes added, but the problem isn't as widespread as I first thought.

(I'll keep plugging through in case I find any other examples)

**Comment by andymantell** [comment]
There are other examples such as this on the select component:

```
  - name: attributes
    hidden: true
    data:
      attributes:
        data-attribute: my data value
```

Which is missing the `items` key which is marked as required in the select component specification. I guess this is acceptable in Nunjucks because this iterating over an undefined value like `{% for item in params.items %}` doesn't error whereas in JavaScript / JSX I would do `items.map((option, index)` which then says `Cannot read property 'map' of undefined`.

I think the way forward would be to validate the examples at some point during the build process. Happy to have a crack at this if people think it's a reasonable idea.

**Comment by andymantell** [comment]
Have done a spike into validating the examples and it's a bit of a can of worms. There are various fields which are marked as "required" but aren't actually treated as such (e.g. html/text or maxlength/maxwords on character-count). There are also some examples which will never validate such as:

```
- name: with falsey values
  hidden: true
  data:
    name: example-name
    items:
      - value: 1
        text: Option 1
      - false
      - null
      - ""
      - value: 2
        text: Option 2
```

So I don't think this is really a useful avenue, not without changing more things than I came here for. You can see the initial spike here: https://github.com/andymantell/govuk-frontend/commit/2245d599e79893aa07a272b12805682c11ee05e1#diff-ec4eb4c51af8d6a320c0398963c9620eR90

I will come at this again with a fresh head on Monday and try to more clearly articulate what I think the actual problem is. I _think_ it basically amounts to fixing the ones that are causing errors in my JavaScript, but that I don't think I should be explicitly catering for as a "third party".
