### ISSUE TITLE
Add required component options to yaml examples

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#1965]
Part of https://github.com/alphagov/govuk-frontend/issues/1962

## Problem
For example: the date input component requires items to have a name or label, but this example has neither:
```
- name: with values
  hidden: true
  data:
    items:
      -
        id: day
      -
        id: month
      -
        id: year
        value: 2018
```

## Checklist

- [x] check the options we mark as required are correct (https://github.com/alphagov/govuk-frontend/pull/1979)
- [ ] add any required options to component examples
