### ISSUE TITLE
Character Count error styling does not match documentation when initialised with `errorMessage`

### ISSUE THREAD

**Issue by JoPintoPaul** [alphagov/govuk-frontend#2588]
## Description of the issue
The [documentation for error styling](https://design-system.service.gov.uk/components/character-count/#error-messages) for a Character Count shows that the following should applied:
- `govuk-textarea--error` applied to the `textarea` (i.e. displays with red border)
- `govuk-hint` removed and `govuk-error-message` applied to the `hint` (i.e. displays in red)
Both of these styles are correctly applied by the Javascript dynamically when text entered into character count exceeds limits.

However, when the component is loaded with an `errorMessage` passed through BUT the characters does not exceed the maximum, the `textarea` and `hint` are not styled as per the documentation.

This is because:
- For the `textarea`, the class `govuk-textarea--error` is applied in the template but then removed as soon as the Javascript initialises, as `updateCountMessage` is called as part of initialisation
- For the `hint`, the default style of `govuk-hint` is hardcoded into the template, and there is no way to override in the template

## Steps to reproduce the issue
You can see this behaviour by adding this example to `character-count.yaml`:
```
- name: with error from model
data:
  name: more-detail
  id: more-detail
  maxlength: 10
  label:
    text: Can you provide more detail?
  errorMessage:
    text: Error message
```

## Actual vs expected behaviour
Actual: Error styling in template does not match documented error styling 
Expected: Error styling matches example in documentation, and error styling when error is dynamically generated

## Environment (where applicable)
- GOV.UK Frontend Version: 4.0.1
