### ISSUE TITLE
Unnecessary CSS is included in IE8 stylesheet

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#3231]
## Cause

Unnecessary CSS, such as repeated style rules and features that are not supported by Internet Explorer 8, is still being included in the IE8-specific stylesheet, despite efforts to automatically remove these features.

Noticed during the 4.5.0 release process.

### Repeated rules
Rules are repeated in several places where media queries have been removed. [postcss-unmq](https://github.com/csstools/postcss-unmq) should be removing the duplicates and only including the rules relevant to the configured screen dimensions (by default, 1024×768)—however this doesn't appear to be happening. 

The presence of both rem and px unit versions is due to [node-pixrem](https://github.com/robwierzbowski/node-pixrem). Having the rem unit versions is unnecessary in the IE8 stylesheet, too. 

```css
.govuk-\!-font-size-19 {
    font-size: 16px!important;
    font-size: 1rem!important;
    line-height: 1.25!important;
    font-size: 19px!important;
    font-size: 1.1875rem!important;
    line-height: 1.31579!important;
}
```

### Unsupported rules
Unsupported CSS rules are still included, such as the flexbox-related rules here.

```css
.govuk-button-group {
    margin-bottom: 15px;
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-right: -15px;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: baseline;
}
```

And `box-shadow` and `box-decoration-break` rules here:

```css
.js-enabled .govuk-accordion__show-all:focus {
    color: #0b0c0c;
    background-color: #fd0;
    box-shadow: 0 -2px #fd0,0 4px #0b0c0c;
    text-decoration: none;
    box-decoration-break: clone;
}
```

### Unsupported selectors
Selectors incorporating the `:not` selector are included in the stylesheet, despite not being supported by IE8.

```css
.govuk-link--no-underline:not(:hover):not(:active) {
    text-decoration: none;
}
```

Same for `:last-child` and `:last-of-type` here.

```css
.govuk-checkboxes__item:last-child,
.govuk-checkboxes__item:last-of-type {
    margin-bottom: 0;
}
```

### Unsupported functions
Several CSS functions not supported by IE8 are still included. In this example, none of `calc()`, `env()` or `max()` are supported in IE8.

```css
@supports (margin:max(calc(0px))) {
    .govuk-width-container {
        margin-right: max(15px,calc(15px + env(safe-area-inset-right)));
        margin-left: max(15px,calc(15px + env(safe-area-inset-left)));
        margin-right: max(30px,calc(15px + env(safe-area-inset-right)));
        margin-left: max(30px,calc(15px + env(safe-area-inset-left)));
    }
}
```

### Third-party browser prefixes
Some browser-prefixed properties and values are still included, despite not being relevant to IE8.

```css
.govuk-link {
    font-family: GDS Transport,arial,sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-decoration: underline;
}
```

### `@supports` at-rule
`@supports` at-rules are included in the stylesheet, despite IE8 not supporting them.

```css
@supports (content-visibility:hidden) {
    .js-enabled .govuk-accordion__section-content[hidden] {
        content-visibility: hidden;
        display: inherit;
    }
}
```

## Consequences

We ship significantly more CSS to IE8 than the browser is capable of using. This may have an exacerbated effect on performance as any contemporary IE8 users are probably running very old hardware and software. 

## Impact of debt

Low

### Reason

Considered as low because:

- There are very, very few IE8 users around nowadays.
- We intend to drop IE8 support in the near future. 
- Unsupported CSS features _should_ be ignored by IE8, though there is no guarantee that the rules fail gracefully, especially compound selectors where only part of the selector is supported.

## Effort to pay down

High

### Reason

Some of these issues could be resolved manually by wrapping the offending code in the `govuk-not-ie8` mixin, so that it's not included in the IE8 stylesheet. 

For others: We currently use the [Oldie](https://github.com/csstools/oldie) plugin to automatically remove unsupported features in the IE8 stylesheet. Oldie appears to be unmaintained, with issues and pull requests not being monitored. We would likely have to fork the plugin or its dependencies if we wanted to make updates to how it works. 

Despite us planning to drop support for IE8 going forward, we will still be supporting it on a security and major bugfix basis for at least a year following the release of Frontend v5. We may want to pay down some of this debt so that things are in a better place before we reduce and drop IE8 support completely. 

## Overall rating

Low
