### ISSUE TITLE
Should errorList be a required field in ErrorSummary component?

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-frontend#3864]
I have a use case where I'm showing a single generic error that isnt tied to a specific form input.

In https://design-system.service.gov.uk/components/notification-banner/ guidance it says to use the Error Summary component.

However the error list is marked as required and if you do not submit an error list you'll get an empty list.

Should this be marked as optional and only output the error list if there's an errorList supplied?

**Comment by NickColley** [comment]
Here's a workaround in SCSS:
```scss
.govuk-error-summary__body p:last-of-type {
    margin-bottom: govuk-spacing(1);
}
.govuk-error-summary__list:not(:has(li)) {
    display: none;
}
.govuk-error-summary__list:has(li) {
    margin-top: govuk-spacing(3);
}
```
