### ISSUE TITLE
Macros Component API should not require internal classes for modifiers

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-frontend#460]
Macros abstract our class names, if we were to change our class names, macro usage would break for our users.

In our button examples, we pass the internal button modifier class to make a button into a start button.

We could consider passing a boolean instead so that if we choose to change how our classes work, macros still function.

For example instead of

```yaml
- name: start
  data:
    text: Start now button
    classes: 'govuk-c-button--start'
```

We could do:

```yaml
- name: start
  data:
    text: Start now button
    start: true
```

See also the GOV.UK Publishing component: http://govuk-static.herokuapp.com/component-guide/button/start_now_button

Link to code: https://github.com/alphagov/static/blob/a9a040a72d475ef7015c1c9e690a5d77687fcfd8/app/views/govuk_component/button.raw.html.erb#L1

We constructed the class based on booleans, then finally merge with `classes` and inject into the markup.

Edit: 
I put together an example showing how you can restructure the macro to avoid the confusing forking logic.

This approach only forks on individual parts of the template, which is easier to reason about.

https://glitch.com/edit/#!/flag-based-macro-approach?path=views/index.html:15:26
