### ISSUE TITLE
Button component without margin overhangs by 2px

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk-frontend#5357]
## Description of the issue

The button component uses a 2px box shadow to provide a visual bottom border. This is used primarily instead of an actual bottom border because the other borders are already defined and this would cause a bevelling issue between the bottom and left/right borders. This means that the button component 'overhangs' by 2px at the bottom.

By default the button component has a margin bottom of 32px, which accounts for this 2px and then adds spacing in line with the spacing scale. However on GOV.UK we use the button component without bottom margin in our search filters, where it is supposed to line up with the bottom of a wrapping element. Due to this 2px of box shadow it doesn't, and we have to insert 2px of padding somewhere to account for this.

This is a very small thing, but if there were a way of preserving the look of the button while allowing it to not have this 2px of overhanging box shadow it would make integrating the button component into edge case scenarios like this a little easier.

## Steps to reproduce the issue

Normal button appearance:

![Screenshot 2024-09-27 at 13 39 15](https://github.com/user-attachments/assets/8fa0aa19-b2de-458a-a989-d9c462484e67)

Button with zero margin applied to the bottom (note 2px overlap with containing element, highlighted):

![Screenshot 2024-09-27 at 13 39 06](https://github.com/user-attachments/assets/76ebdc8f-353e-4036-80c0-6918477cc91a)

Use of button in GOV.UK search (mobile view) at bottom of containing element, note slight overlap/misalign with grey left border of container:

![Screenshot 2024-09-27 at 13 40 36](https://github.com/user-attachments/assets/696e4503-ab9d-41f5-a0b3-3e48fb852f7b)

## Environment (where applicable)

- Operating system: N/A
- Browser: N/A
- Browser version: N/A
- GOV.UK Frontend Version: current (v5.6)

**Comment by romaricpascal** [comment]
Something we may want to try is drawing the shadow using a solid `linear-gradient`:

```scss
.govuk-button {
  background-image: linear-gradient(#002d18);
  background-repeat: repeat-x; // We want to repeat horizontally to properly reach the edges
  background-size: 2px 2px;  
  background-position: bottom;
  background-origin: border-box; // Allow the background to be drawn under the bottom border
}
```

**Comment by romaricpascal** [comment]
If we explore [border radius](https://github.com/alphagov/govuk-frontend/pull/6315), we'll need to think about how they affect the technique we pick. A flat linear gradient would for example not be rounded on the left and right.

<img width="719" height="381" alt="Screenshot of 3 buttons with rounded corners and different techniques to display the bottom border" src="https://github.com/user-attachments/assets/cb2ff635-0540-438b-b488-9cc604e655b9" />

<details>
	<summary>Code in the screenshot</summary>

```css
.govuk-button ~ .govuk-button {
  margin-left: 10px;
  box-shadow: none;
  padding-bottom: 9px;
}

.govuk-button:nth-child(2) {
  background-image: linear-gradient(#002d18);
  background-repeat: repeat-x; 
  background-size: 2px 2px;  
  background-position: bottom;
  background-origin: border-box;
}

.govuk-button:nth-child(3) {
  &::after {
    content: '';
    position:absolute;
    bottom: 0;
    left: -2px;
    right: -2px;
    top: 0;
    box-shadow: 0 2px 0 #002d18;
    border-radius: inherit;
  }
}

```
</details>

**Comment by finchello** [comment]
Hi 👋 I'd like to pick this up as my first contribution, if it's still available.

From the thread, the suggested direction is to replace the 2px box-shadow with a solid linear-gradient background so the button no longer overhangs by 2px when bottom margin is removed. Before I open a PR, two quick checks: (1) Is the linear-gradient approach (drawn with background-origin: border-box) still the preferred solution, or would you rather wait until the border-radius work is settled, given the rounded corners caveat raised above? (2) Are there any visual regression tests I should update or add alongside the change?

Happy to follow whatever direction the team prefers. Thanks!

**Comment by romaricpascal** [comment]
Hi @finchello. Thanks for offering to help, however, this is something we'd prefer handling within the team. Changing the rendering of the button would have impact across our whole Design System and we want to make sure we'll consider all the angles before doing so.

**Comment by finchello** [comment]
No problem at all, thanks for the quick reply and the context — that makes sense given the cross-Design-System impact. I'll keep an eye out for other ways to help. Thanks!

**Comment by NickColley** [comment]
Worth noting that the Button group has some special spacing to account for this so if we made any changes we'd want to check the Button group too.

Also we could maybe achieve this by using an inset box-shadow, but we'd need to remove the border, which is likely used in high contrast mode so maybe we'd want to add transparent outline or something like this.

```css
.govuk-button {
    box-shadow: inset 0 -2px 0 #083d29;
    border: none;
    padding: 10px 12px 11px;
}
```

Perhaps if we added the box-shadow to the currently invisible overlay that could allow for what we need.
