### ISSUE TITLE
govuk-section-break line width is too large

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#577]
Section breaks are 2px in width when they should only be 1px in width.

<img width="645" alt="screen shot 2018-03-06 at 10 17 24" src="https://user-images.githubusercontent.com/2445413/37026865-9942bbea-2127-11e8-9195-2511ae0c1c7d.png">

I imagine it just needs changing from 

```css
.class {
  border: 1px solid grey;
}
```

to

```css
.class {
  border: 0;
  border-bottom: 1px solid grey;
}
```
