### ISSUE TITLE
Should label in Nunjucks be wrapped in a condition?

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#714]
The following code
```
{{ govukInput({
   "id": "national-insurance-number",
   "name": "national-insurance-number",
 }) }}
```
will output
```
<div class="govuk-form-group">
  <label class="govuk-label" for="govuk-input-a">
    
  </label>
  <input class="govuk-input" id="govuk-input-a" name="national-insurance-number" type="text">
</div>
```
Empty label, that has a 5px bottom margin, which will effect any alignment

In the input component template we currently  don't wrap label in a condition, like we do hint and error message.

**Comment by nickcolley** [comment]
Ideally not having a label input would result in a hard failure with a visible error.

If anything we could consider doing something like

```css
.govuk-label:empty::after {
  content: "Warning: No label for input";
  color: red;
  font-weight: bold;
}
```
