### ISSUE TITLE
Stop specifying black colour for plain elements and basic components

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#954]
Currently, lots of elements, including a basic `p` with no class, and classes like `govuk-list`, set an explicit foreground colour of black.

This means that if you include these elements within a container which specifies a different background and foreground colour (say, white on blue), you have to override the colours of all the elements within it, eg:

```css
.my-container {
  color: govuk-colour("white");
  background-color: govuk-colour("blue");

  p, a, .govuk-list, .govuk-heading-s {
    color: inherit;
  }
}
```

...this seems a tad unexpected, and makes for harder to maintain code (as you keep having to add to the list of things which should inherit the colour whenever the content changes).  My expectation was that the black foreground colour (and white background colour) would be set on a high-level container element (like `.govuk-template__body`), and other black text would just inherit from that.

However, perhaps there’s a reason why you’ve implemented it this way?

Either way, I figured it'd be useful to have the discussion... 😄
